// x FlexAlign FlexAlign.Start FlexAlign.Center FlexAlign.End
//   FlexAlign.SpaceAround FlexAlign.SpaceBetween FlexAlign.SpaceEvenly

//y ItemAlign.Auto ItemAlign.Center ItemAlign.End ItemAlign.Stretch ItemAlign.Baseline


// justifyContent: FexAlign.xxx wrap: FlexWrap:xxx alignCentent: FlexAlign.Start

// .flexBasis('auto') 未设置width以及为auto时，内容为自身宽度
//                    设置了width以及为auto时，内容为width值
// .flexBasis(100) 未设置width以及flexBasis为100，宽度为100vp
// .flexGrow 设置父容器的剩余空间分配给次属性所在的组件比例

// .flexShrink(3) 当父组件空间不足时，字句间压缩比例
